name: Bug report
description: Report a problem in Abrid
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect vs what happened?
      placeholder: Clear steps to reproduce
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: macOS / Node version / etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
